#!/usr/bin/env python3
"""
Indian Stock Market News Aggregator
Fetches news from multiple Indian financial sources and sends via email
"""

import feedparser
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Indian Financial News RSS Feeds
NEWS_SOURCES = {
    'Moneycontrol Markets': 'https://www.moneycontrol.com/rss/marketreports.xml',
    'Economic Times Markets': 'https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms',
    'Business Standard Markets': 'https://www.business-standard.com/rss/markets-106.rss',
    'Mint Markets': 'https://www.livemint.com/rss/markets',
    'NDTV Profit': 'https://feeds.feedburner.com/ndtvprofit-latest',
}

def fetch_news(max_articles_per_source=5):
    """Fetch news from all sources"""
    all_news = []
    
    for source_name, feed_url in NEWS_SOURCES.items():
        try:
            feed = feedparser.parse(feed_url)
            articles = []
            
            for entry in feed.entries[:max_articles_per_source]:
                article = {
                    'title': entry.get('title', 'No Title'),
                    'link': entry.get('link', '#'),
                    'published': entry.get('published', 'N/A'),
                    'summary': entry.get('summary', entry.get('description', 'No summary available'))[:200] + '...'
                }
                articles.append(article)
            
            all_news.append({
                'source': source_name,
                'articles': articles
            })
            print(f"✓ Fetched {len(articles)} articles from {source_name}")
            
        except Exception as e:
            print(f"✗ Error fetching from {source_name}: {e}")
    
    return all_news

def create_html_email(news_data):
    """Create HTML formatted email"""
    
    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #e74c3c;
                margin-top: 30px;
                border-left: 4px solid #e74c3c;
                padding-left: 10px;
            }}
            .article {{
                margin: 15px 0;
                padding: 15px;
                background-color: #f9f9f9;
                border-left: 3px solid #3498db;
                border-radius: 4px;
            }}
            .article-title {{
                font-weight: bold;
                font-size: 16px;
                color: #2c3e50;
                margin-bottom: 5px;
            }}
            .article-title a {{
                color: #2c3e50;
                text-decoration: none;
            }}
            .article-title a:hover {{
                color: #3498db;
            }}
            .article-meta {{
                color: #7f8c8d;
                font-size: 12px;
                margin-bottom: 8px;
            }}
            .article-summary {{
                color: #555;
                font-size: 14px;
            }}
            .footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 2px solid #ecf0f1;
                text-align: center;
                color: #7f8c8d;
                font-size: 12px;
            }}
        </style>
    </head>
    <body>
        <h1>📈 Indian Stock Market News - {datetime.now().strftime('%B %d, %Y')}</h1>
        <p>Good morning! Here's your daily digest of Indian stock market news.</p>
    """
    
    for source_data in news_data:
        html += f"<h2>📰 {source_data['source']}</h2>"
        
        if not source_data['articles']:
            html += "<p><em>No articles available</em></p>"
            continue
        
        for article in source_data['articles']:
            html += f"""
            <div class="article">
                <div class="article-title">
                    <a href="{article['link']}" target="_blank">{article['title']}</a>
                </div>
                <div class="article-meta">📅 {article['published']}</div>
                <div class="article-summary">{article['summary']}</div>
            </div>
            """
    
    html += """
        <div class="footer">
            <p>💡 Generated by Financial News Aggregator</p>
            <p>This is an automated daily digest of Indian stock market news</p>
        </div>
    </body>
    </html>
    """
    
    return html

def send_email(html_content, recipient_email):
    """Send email using SMTP"""
    
    sender_email = os.getenv('SENDER_EMAIL')
    sender_password = os.getenv('SENDER_PASSWORD')
    smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
    smtp_port = int(os.getenv('SMTP_PORT', '587'))
    
    if not sender_email or not sender_password:
        print("❌ Email credentials not configured!")
        print("Please set SENDER_EMAIL and SENDER_PASSWORD in .env file")
        return False
    
    # Create message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"📈 Indian Stock Market News - {datetime.now().strftime('%B %d, %Y')}"
    msg['From'] = sender_email
    msg['To'] = recipient_email
    
    # Attach HTML content
    html_part = MIMEText(html_content, 'html')
    msg.attach(html_part)
    
    # Send email
    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print(f"✓ Email sent successfully to {recipient_email}")
        return True
    except Exception as e:
        print(f"✗ Error sending email: {e}")
        return False

def save_html_locally(html_content, filename='latest_news.html'):
    """Save HTML to local file for preview"""
    filepath = os.path.join(os.path.dirname(__file__), filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"✓ Saved HTML preview to {filepath}")
    return filepath

def main():
    """Main function"""
    print("=" * 60)
    print("📈 Indian Stock Market News Aggregator")
    print("=" * 60)
    print()
    
    # Fetch news
    print("Fetching news from sources...")
    news_data = fetch_news(max_articles_per_source=5)
    print()
    
    # Create HTML
    print("Creating email content...")
    html_content = create_html_email(news_data)
    print("✓ Email content created")
    print()
    
    # Save locally for preview
    html_file = save_html_locally(html_content)
    print()
    
    # Send email
    recipient_email = os.getenv('RECIPIENT_EMAIL')
    
    if recipient_email:
        print(f"Sending email to {recipient_email}...")
        send_email(html_content, recipient_email)
    else:
        print("⚠️  RECIPIENT_EMAIL not set in .env file")
        print("Email not sent, but HTML preview saved locally")
        print(f"Open {html_file} in your browser to preview")
    
    print()
    print("=" * 60)
    print("✓ Done!")
    print("=" * 60)

if __name__ == '__main__':
    main()
